export const CHANGE_EXISTS_CURRENT_USER = "CHANGE_EXISTS_CURRENT_USER";
export const CHANGE_CURRENT_USER = "CHANGE_CURRENT_USER";
export const VALIDATE_STATUS_INPUTS = "VALIDATE_STATUS_INPUTS";
export const RESET_ERROR_MESSAGE="RESET_ERROR_MESSAGE"
